-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 10:56:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `Projeto_integrador` ;

-- -----------------------------------------------------
-- Table `Projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_integrador`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `usuario_email` VARCHAR(350) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_integrador`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_integrador`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_integrador`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_integrador`.`tb_postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(500) NULL,
  `descricao` VARCHAR(2000) NOT NULL,
  `anexos` VARCHAR(255) NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  `tb_tema_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagens_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_tema1_idx` (`tb_tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `Projeto_integrador`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_tema1`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `Projeto_integrador`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
